# Generated by Django 5.2.10 on 2026-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('driving', models.PositiveSmallIntegerField(default=50)),
                ('approach', models.PositiveSmallIntegerField(default=50)),
                ('short_game', models.PositiveSmallIntegerField(default=50)),
                ('putting', models.PositiveSmallIntegerField(default=50)),
                ('volatility', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
