# Generated by Django 5.2.10 on 2026-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='handedness',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left')], default='R', max_length=1),
        ),
    ]
