# Generated by Django 5.2.10 on 2026-01-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfers', '0003_remove_golfer_driving_golfer_ball_striking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
