# Generated by Django 5.2.10 on 2026-01-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('golfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='setup', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('current_time', models.DateTimeField()),
                ('current_round', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_time', models.DateTimeField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('is_human', models.BooleanField(default=False)),
                ('total_strokes', models.IntegerField(default=0)),
                ('thru_hole', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cut', models.BooleanField(default=False)),
                ('golfer', models.ForeignKey(blank=True, help_text='Null if this is a human player', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfers.golfer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='HoleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('hole_number', models.PositiveSmallIntegerField()),
                ('strokes', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_results', to='tournaments.tournamententry')),
            ],
            options={
                'ordering': ['round_number', 'hole_number'],
                'unique_together': {('entry', 'round_number', 'hole_number')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.group')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamententry')),
            ],
            options={
                'unique_together': {('group', 'entry')},
            },
        ),
    ]
