# Generated by Django 5.2.10 on 2026-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='current_hole',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='holes_completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='next_action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='start_hole',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
