# Generated by Django 5.2.10 on 2026-01-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_group_current_hole_group_holes_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cut_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cut_size',
            field=models.PositiveSmallIntegerField(default=65),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='sim_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
