# Generated by Django 5.2.10 on 2026-01-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_cut_applied_tournament_cut_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='wave',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
