# Generated by Django 5.2.10 on 2026-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_group_wave'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamententry',
            name='tournament_strokes',
            field=models.IntegerField(default=0),
        ),
    ]
