# Generated by Django 5.2.10 on 2026-01-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamententry_tournament_strokes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamententry',
            name='avatar_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='country',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='handedness',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], default='R', max_length=1),
        ),
    ]
