# Generated by Django 5.2.10 on 2026-01-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_holeresult_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('stroke', 'Stroke Play'), ('match', 'Match Play (Ryder Cup)')], default='stroke', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='team',
            field=models.CharField(blank=True, default='', help_text='USA or EUR for Match Play', max_length=10),
        ),
    ]
