# Generated by Django 5.2.10 on 2026-01-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournament_session_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='projected_cut_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('playoff', 'Playoff')], default='setup', max_length=20),
        ),
    ]
