# Generated by Django 5.2.10 on 2026-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournament_projected_cut_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round_conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
