# Generated by Django 5.2.10 on 2026-01-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_round_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='live_win_probs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
