# Generated by Django 5.2.10 on 2026-01-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('difficulty_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('greens_speed', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fairway_firmness', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rough_severity', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('par', models.PositiveSmallIntegerField()),
                ('stroke_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('elevation_change', models.SmallIntegerField(default=0)),
                ('dogleg', models.CharField(choices=[('none', 'None'), ('left', 'Left'), ('right', 'Right')], default='none', max_length=10)),
                ('fairway_width', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('green_size', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('green_slope', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('bunker_count', models.PositiveSmallIntegerField(default=0)),
                ('water_in_play', models.BooleanField(default=False)),
                ('trees_in_play', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TeeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('yardage', models.PositiveSmallIntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('slope', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tee_boxes', to='courses.hole')),
            ],
            options={
                'ordering': ['hole__number', 'name'],
                'unique_together': {('hole', 'name')},
            },
        ),
    ]
